# Generated by Django 3.1.5 on 2021-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Name', models.CharField(max_length=30, null=True)),
                ('U_Surname', models.CharField(max_length=30, null=True)),
                ('U_Age', models.IntegerField(blank=True, null=True)),
                ('U_ContactNo', models.TextField(blank=True, max_length=15, null=True)),
                ('U_ChildCount', models.IntegerField(blank=True, null=True)),
                ('U_BankType', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
