# Generated by Django 3.1.5 on 2021-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApi', '0002_auto_20210623_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='U_ContactNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
