# Generated by Django 3.1.5 on 2021-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApi', '0003_auto_20210623_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='U_BankType',
            new_name='U_Area',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='U_ChildCount',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='U_Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='U_Gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='U_Race',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
